
version: '3.2'

services:

  laravel:
    build: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/:cached 
    container_name: laravel
    networks:
      - default

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: camaro
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - database_volume:/var/lib/mysql
    networks: 
      - default

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    links:
      - mysql:mysql
    environment:
      PMA_HOST: mysql
    networks: 
      - default
  
  api:
    build: ./api
    volumes:
      - ./api:/api
    ports:
      - "5000:5000"
    networks:
      - default

networks: 
  default:

volumes: 
    database_volume: