version: "3.3"

services:
  laravel:
    build: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/:cached 
    container_name: laravel1
    networks: 
        - default

  database:
    image: mysql:8.0.21
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE='camaro'
      - MYSQL_ROOT_PASSWORD='root'
    volumes:
      - myapp:/var/lib/mysql
    container_name: database1
    networks: 
        - default

networks: 
    default:

volumes:
  myapp: