
version: '3.2'

services:

  laravel:
    build: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/:cached 
    container_name: laravel1
    networks: 
      - default

  db:
    image: mysql:8.0
    container_name: appsDB
    restart: always
    ports:
      - '6603:3306'
    environment:
      MYSQL_ROOT_PASSWORD: helloworld

  app:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
  
  flask:
    build: .
    ports:
      - "5000:5000"