
version: '3.2'

services:

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "10000:8080"
    volumes:
      - ./frontend:/var/www/html/:cached 
    networks:
      - default

  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: camaro
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - database_volume:/var/lib/mysql
    networks: 
      - default

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    links:
      - mysql:mysql
    environment:
      PMA_HOST: mysql
    networks: 
      - default
  
  api:
    container_name: api
    build: ./api
    volumes:
      - ./api:/api
    ports:
      - "5000:5000"
    networks:
      - default

  auth:
    container_name: auth
    build: ./authentication
    volumes:
      - ./authentication:/var/www/
      - ./authentication/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "4000:80"
    networks:
      - default
  
  promo:
    container_name: promo
    build: ./promo
    volumes:
      - ./promo:/var/www/html/
    ports:
      - "3000:80"
    networks:
      - default

networks: 
  default:

volumes: 
    database_volume: