apiVersion: v1
kind: Pod
metadata:
  name: camaro-security
  labels:
    app: web
spec:
  containers:
    - name: api
      imagePullPolicy: Never
      image: api:1.0
      ports:
        - containerPort: 5000